name: auto-merge
on: [pull_request_target]

jobs:
  auto-merge:
    uses: project-calavera/calavera-reusable-actions/.github/workflows/auto-merge.yml@main
    with:
      target-repo: "TODO: add the name of the current (origin) repo"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
